name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        registry: docker.pkg.github.com/
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        repository: gopinnath/trenzz-summarize
        tags: trenzz 
        dockerfile: src/main/docker/Dockerfile.mvn
