# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Build with Maven
      run: mvn -B package -Pnative -Dquarkus.native.container-build=true
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        registry: docker.pkg.github.com
        username: gopinnath
        password: ${{ secrets.PASSWORD }}
        repository: gopinnath/trenzz-summarize/trenzz
        tags: n1.0
        dockerfile: src/main/docker/Dockerfile.native
